id: state_management_quiz
learningObjectives:
  - Test knowledge on what hooks are used for state management.
hints:
  - Consider the hooks that deal directly with state management.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Which of the following hooks is used for state management in React?
    - actionId: quiz_message
      name: quiz
      params:
        person: lucca
        options:
          - useContext
          - useReducer
          - useEffect
trigger:
  type: chat_form_submitted
  flowNode:
    switch:
      key: ${formSubmission}
      cases:
        A:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Close, useContext deals with context, not direct state management. Try
                      again!
            - actionId: replay_action
              params:
                actionName: quiz
        B:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Correct! useReducer is great for more complex state management scenarios.
            - actionId: finish_step
        C:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Not quite, useEffect is for handling side-effects. Give it another shot!
            - actionId: replay_action
              params:
                actionName: quiz
